### PR TITLE
Be more serious about first timers

### PR DESCRIPTION
**Pull request by todb-r7**
If we advertise a pass on the first time, I fear we will attract out of town tourists, especially around large events such as SXSWi. We should be explicit about this rule on the Internet, regardless of how strongly it's actually enforced on site.

### CODE REVIEW

**Comment by todb-r7** [comment]
@mauvehed wake up

**Comment by mauvehed** [comment]
SOME OF US HAVE JOBS YOU KNOW! We don't all sit around in our underwear at home! I only get to do that some days of the week, the rest I have to be onsite. Sheesh.

**Comment by todb-r7** [comment]
Thank you @mauvehed for your kind and attentive service.

**Comment by mauvehed** [comment]
<3 @todb-r7

**Pull request merged**
