### PR TITLE
Create cve page

### PR DESCRIPTION
**Pull request by todb**
Put in the skeleton of a VDP and CVE collection area for the website.

It's okay that the VDP is blank for now, because we don't actually have one. We'll bang one out.

I /think/ the links to `meetings` and `rules` should Just Work, undecorated, but need to double-check.

### CODE REVIEW

**Review by mauvehed — COMMENTED** [review]
To define undecorated links you can do so in the config

https://github.com/AustinHackers/austinhackers.github.io/blob/main/_config.yml

I'm on mobile at the moment.

**Review by mauvehed — COMMENTED** [review]
Shouldn’t all email references be aha@takeonme.org?

**Comment by todb** [comment]
Oh sure. So basically we want two aliases.

cve@takeonme.org - CVE specific stuff. CVE program really likes having a special alias for CVE things.

aha@takeonme.org - Everything else.

I can fix https://takeonme.org/.well-known/security.txt as well.

**Comment by todb** [comment]
Fixed and also updated `security.txt`

**Review by mauvehed — APPROVED** [review]

**Pull request merged**
