### PR TITLE
Add FXBG Hackers to Our Spawn list

### PR DESCRIPTION
**Pull request by evanottinger**
Hello! Myself, TinkerSec, and molware1 have co-organized FXBG Hackers Association as a fork off of the Dallas Hackers Association. This PR adds our information to your "Our Spawn" list.

### CODE REVIEW

**Comment by mauvehed** [comment]
I’m torn here, because you have failed the foundational piece of naming a HA chapter.. That is, the acronym ending in some kind of exclamation, *HA! Such as AHA! Or HAHA! One variation of this that was actually my favorite was the previous Dallas Order of Hackers, or DOH! That one was absolutely beautiful.

FXBG is.. uh.. verbal diarrhea?

Thoughts @todb?

**Comment by evanottinger** [comment]
Understandable. FXBG is the common abbreviation for "Fredericksburg, VA" by the local types. Our actual acronym is FHA--which is a nested acronym. We forked off of DHA, which is why we don't have the !

Is this acceptable?

**Comment by todb** [comment]
Yes!

**Comment by mauvehed** [comment]
Nested is great because its annoying/clever.. I love it! FHA it is!

**Review by mauvehed — APPROVED** [review]

**Pull request merged**
